CREATE DATABASE projeto_pratica;
GO

USE projeto_pratica;
GO

-- Table: COND_PAGAMENTO
CREATE TABLE COND_PAGAMENTO (
    CONDPAG_ID INT IDENTITY(1,1) PRIMARY KEY,
    CONDPAG_DESC NVARCHAR(255) NOT NULL,
    CONDPAG_PARCELAS INT NOT NULL
);
GO

-- Table: FORMA_PAGAMENTO
CREATE TABLE FORMA_PAGAMENTO (
    FORMAPAG_ID INT IDENTITY(1,1) PRIMARY KEY,
    FORMAPAG_DESC NVARCHAR(255) NOT NULL
);
GO

-- Table: PARCELA_CONDPAG (Updated)
CREATE TABLE PARCELA_CONDPAG (
    PARCELA_ID INT IDENTITY(1,1) PRIMARY KEY,
    CONDPAG_ID INT NOT NULL,
    FORMAPAG_ID INT NOT NULL,
    PARCELA_PERCT DECIMAL(5,2) NOT NULL,  -- Percentage of the total amount
    PARCELA_NUM INT NOT NULL,             -- Installment number
    PARCELA_PRAZO INT NOT NULL,           -- Payment term (days)

    -- Foreign Key Constraints
    CONSTRAINT FK_PARCELA_CONDPAG FOREIGN KEY (CONDPAG_ID) 
        REFERENCES COND_PAGAMENTO (CONDPAG_ID) ON DELETE CASCADE,

    CONSTRAINT FK_PARCELA_FORMAPAG FOREIGN KEY (FORMAPAG_ID) 
        REFERENCES FORMA_PAGAMENTO (FORMAPAG_ID) ON DELETE CASCADE
);
GO

-- Table: PAIS
CREATE TABLE PAIS (
    PAIS_ID INT IDENTITY(1,1) PRIMARY KEY,
    PAIS_NOME NVARCHAR(255) NOT NULL,
    PAIS_SIGLA NVARCHAR(10),
    PAIS_MOEDA NVARCHAR(50),
    PAIS_DDI NVARCHAR(10)
);
GO

-- Table: ESTADO
CREATE TABLE ESTADO (
    ESTADO_ID INT IDENTITY(1,1) PRIMARY KEY,
    ESTADO_NOME NVARCHAR(255) NOT NULL,
    ESTADO_UF NVARCHAR(5) NOT NULL,
    PAIS_ID INT NOT NULL,

    CONSTRAINT FK_ESTADO_PAIS FOREIGN KEY (PAIS_ID)
        REFERENCES PAIS (PAIS_ID) ON DELETE CASCADE
);
GO

-- Table: CIDADE
CREATE TABLE CIDADE (
    CIDADE_ID INT IDENTITY(1,1) PRIMARY KEY,
    CIDADE_NOME NVARCHAR(255) NOT NULL,
    CIDADE_DDD NVARCHAR(5),
    ESTADO_ID INT NOT NULL,

    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ESTADO_ID)
        REFERENCES ESTADO (ESTADO_ID) ON DELETE CASCADE
);
GO

CREATE TABLE CLIENTE (
    CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,

    CLIENTE_TIPO CHAR(1) NOT NULL,
    CLIENTE_NOME_RS NVARCHAR(255) NOT NULL,
    CLIENTE_APELIDO_FANTASIA NVARCHAR(255),
    CLIENTE_NASCIMENTO DATE NOT NULL,
    CLIENTE_CPF_CNPJ NVARCHAR(20) NOT NULL,
    CLIENTE_RG_INSCR NVARCHAR(20),
    CLIENTE_EMAIL NVARCHAR(255),
    CLIENTE_TELEFONE NVARCHAR(20),
    CLIENTE_STATUS BIT NOT NULL,
    CLIENTE_ESTRANGEIRO BIT NOT NULL,
	CLIENTE_ENDERECO NVARCHAR(255) NOT NULL,
    CLIENTE_BAIRRO NVARCHAR(100) NOT NULL,
    CLIENTE_CEP NVARCHAR(20) NOT NULL,


    CIDADE_ID INT NOT NULL,

    CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (CIDADE_ID)
        REFERENCES CIDADE(CIDADE_ID)
);
GO

	CREATE TABLE FUNCIONARIO (
		FUNCIONARIO_ID INT IDENTITY(1,1) PRIMARY KEY,

		FUNCIONARIO_TIPO CHAR(1) NOT NULL,
		FUNCIONARIO_NOME NVARCHAR(255) NOT NULL,
		FUNCIONARIO_APELIDO VARCHAR(255),
		FUNCIONARIO_NASCIMENTO DATE NOT NULL,
		FUNCIONARIO_CPF VARCHAR(20) NOT NULL,
		FUNCIONARIO_RG VARCHAR(20),
		FUNCIONARIO_EMAIL NVARCHAR(255),
		FUNCIONARIO_TELEFONE NVARCHAR(20),
		FUNCIONARIO_STATUS BIT NOT NULL,
		FUNCIONARIO_ESTRANGEIRO BIT NOT NULL,

		FUNCIONARIO_ENDERECO NVARCHAR(255),
		FUNCIONARIO_BAIRRO NVARCHAR(100),
		FUNCIONARIO_CEP NVARCHAR(15),

		FUNCIONARIO_MATRICULA NVARCHAR(50),
		FUNCIONARIO_CARGO NVARCHAR(100),
		FUNCIONARIO_SALARIO_BRUTO FLOAT,
		FUNCIONARIO_SALARIO_LIQUIDO FLOAT,
		FUNCIONARIO_DATA_ADMISSAO DATE,
		FUNCIONARIO_CARGA_HORARIA INT,

		CIDADE_ID INT NOT NULL,

		CONSTRAINT FK_FUNCIONARIO_CIDADE FOREIGN KEY (CIDADE_ID)
			REFERENCES CIDADE(CIDADE_ID)
	);
	GO